name: Scrape status-ovhcloud.com pages

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '*/10 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      id: checkout
      uses: actions/checkout@v2
      
    - name: Fetch latest data
      id: scrap
      run: |-
        ./scrape_status-ovhcloud.sh

    - name: Commit and push if it changed
      id: commit
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -uR)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
